stages:
  - rdf
  - validate
  - cv
  - pages
  - upload

rdf:
  image:
    name: mathiasvda/logseq-rdf-export
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: rdf
  script:
    - echo "The following line is to avoid a check in logseq-rdf-export targetting github actions"
    - unset CI
    - logseq-rdf-export matdata-expertise-raw.ttl --directory $CI_PROJECT_DIR
  artifacts:
    paths:
      - matdata-expertise-raw.ttl

validate:
  image: python:3.12.8-slim
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: validate
  script:
    - pip install -r ./kg-actions/requirements.txt
    - python ./kg-actions/clean-graph.py
    - python ./kg-actions/validate-graph.py
  dependencies:
    - rdf
  artifacts:
    paths:
      - matdata-expertise.ttl
      - matdata-expertise-raw.ttl

cv:
  image: mathiasvda/rendercv-with-profile-pic
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: cv
  script:
    - cd cv
    - pip install -r requirements.txt
    - python3.12 ./complete-cv.py
    - rendercv render -nomd -nohtml -nopng Mathias_Vanden_Auweele_CV.yaml
  dependencies:
    - validate
  artifacts:
    paths:
      - cv/rendercv_output/
      - cv/Mathias_Vanden_Auweele_CV.yaml

pages:
  image:
    name: ghcr.io/l-trump/logseq-publish-spa:alpine
    entrypoint: ["/bin/sh", "-c"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: pages
  environment: live
  script:
    - mkdir -p public
    - node /opt/logseq-publish-spa/publish_spa.mjs $CI_PROJECT_DIR/public --static-directory /opt/logseq-static --directory $CI_PROJECT_DIR --theme-mode $THEME --accent-color $ACCENT_COLOR
    - mv matdata-expertise.ttl public/static/
    - mv matdata-expertise-raw.ttl public/static/
    - ls cv/rendercv_output/
    - mv cv/rendercv_output/Mathias_Vanden_Auweele_CV.pdf public/static/
  artifacts:
    paths:
      - public
  dependencies:
    - rdf
    - cv
    - validate

upload:
  stage: upload
  script:     
    - |
      curl -X POST \
      -H "Authorization: Basic ${JENA_AUTH}" \
      --data "update=delete%20where%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D" \
      https://jena.mkwadraat.be/expertise/update      
    - |
        curl -X POST \
        -H "Authorization: Basic ${JENA_AUTH}" \
        -H "Content-Type: text/turtle" \
        --data-binary @matdata-expertise.ttl \
        https://jena.mkwadraat.be/expertise/data
  dependencies:
    - rdf
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

