
stages:
  - rdf
  - cv
  - pages

rdf:
  image:
    name: mathiasvda/logseq-rdf-export
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: rdf
  script:
    - echo "The following line is to avoid a check in logseq-rdf-export targetting github actions"
    - unset CI
    - logseq-rdf-export matdata-expertise.ttl --directory $CI_PROJECT_DIR
  artifacts:
    paths:
      - matdata-expertise.ttl

cv:
  image: mathiasvda/rendercv-with-profile-pic
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: cv
  script:
    - cd cv
    - pip install -r requirements.txt
    - python3.12 ./complete-cv.py
    - rendercv render -nomd -nohtml -nopng Mathias_Vanden_Auweele_CV.yaml
  dependencies:
    - rdf
  artifacts:
    paths:
      - cv/rendercv_output/
      - cv/Mathias_Vanden_Auweele_CV.yaml

pages:
  image:
    name: ghcr.io/l-trump/logseq-publish-spa:alpine
    entrypoint: ["/bin/sh", "-c"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: pages
  environment: live
  script:
    - mkdir -p public
    - node /opt/logseq-publish-spa/publish_spa.mjs $CI_PROJECT_DIR/public --static-directory /opt/logseq-static --directory $CI_PROJECT_DIR --theme-mode $THEME --accent-color $ACCENT_COLOR
    - mv matdata-expertise.ttl public/static/
    - mv rendercv_output/Mathias_Vanden_Auweele_CV.pdf public/static/
  artifacts:
    paths:
      - public
  dependencies:
    - rdf
    - cv